# Generated by Django 4.1.3 on 2023-03-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('дом', 'дом'), ('квартира', 'квартира'), ('земельный участок', 'земельный участок')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('material', models.CharField(choices=[('дерево', 'дерево'), ('кирпич', 'кирпич'), ('керамические блоки', 'керамические блоки'), ('газобетон', 'газобетон')], max_length=255)),
                ('rooms', models.IntegerField()),
                ('furniture', models.CharField(choices=[('С мебелью', 'С мебелью'), ('Без мебели', 'Без мебели'), ('Частично', 'Частично'), ('Только кухня', 'Только кухня'), ('Только санузел', 'Только санузел')], max_length=20)),
                ('repair', models.CharField(choices=[('Евро ремонт', 'Евро ремонт'), ('Черновая отделка', 'Черновая отделка'), ('Без ремонта', 'Без ремонта'), ('Частичная отделка', 'Частичная отделка')], max_length=20)),
                ('near', models.TextField(blank=True, null=True)),
                ('date_of_building', models.IntegerField(blank=True, max_length=4, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('storeys', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(choices=[('Новостройка', 'Новостройка'), ('Панельный дом', 'Панельный дом'), ('Кирпичный дом', 'Кирпичный дом')], max_length=20)),
                ('living_space', models.IntegerField(null=True)),
                ('location', models.CharField(choices=[('В городе', 'В городе'), ('Пригород', 'Пригород'), ('За городом', 'За городом')], max_length=20)),
                ('convenience', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('image7', models.ImageField(null=True, upload_to='')),
                ('image8', models.ImageField(null=True, upload_to='')),
                ('image9', models.ImageField(null=True, upload_to='')),
                ('image10', models.ImageField(null=True, upload_to='')),
                ('image11', models.ImageField(null=True, upload_to='')),
                ('image12', models.ImageField(null=True, upload_to='')),
                ('image13', models.ImageField(null=True, upload_to='')),
                ('image14', models.ImageField(null=True, upload_to='')),
                ('image15', models.ImageField(null=True, upload_to='')),
                ('image17', models.ImageField(null=True, upload_to='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.house')),
            ],
        ),
    ]
