# Generated by Django 4.1.6 on 2023-02-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_kvartira_house_ptr_delete_dacha_delete_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('furniture', models.BooleanField(default=False)),
                ('repair', models.BooleanField(blank=True, default=False, null=True)),
                ('near', models.TextField(blank=True, null=True)),
                ('date_of_building', models.IntegerField(blank=True, max_length=4, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('storeys', models.IntegerField(blank=True, null=True)),
                ('living_space', models.IntegerField(null=True)),
                ('location', models.BooleanField(default=False, null=True)),
                ('convenience', models.TextField(null=True)),
                ('building_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.building_type')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.material')),
            ],
        ),
    ]
