# Generated by Django 4.1.6 on 2023-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_type_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Building_type',
        ),
    ]
