# Generated by Django 4.1.6 on 2023-02-13 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0008_alter_house_building_type_delete_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
