# Generated by Django 4.1.6 on 2023-02-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_alter_house_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.CharField(choices=[('Новостройка', 'Новостройка'), ('Панельный дом', 'Панельный дом'), ('Кирпичный дом', 'Кирпичный дом')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='furniture',
            field=models.CharField(choices=[('С мебелью', 'С мебелью'), ('Без мебели', 'Без мебели'), ('Частично', 'Частично'), ('Только кухня', 'Только кухня'), ('Только санузел', 'Только санузел')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(choices=[('В городе', 'В городе'), ('Пригород', 'Пригород'), ('За городом', 'За городом')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='repair',
            field=models.CharField(choices=[('Евро ремонт', 'Евро ремонт'), ('Черновая отделка', 'Черновая отделка'), ('Без ремонта', 'Без ремонта'), ('Частичная отделка', 'Частичная отделка')], max_length=20),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
    ]
