# Generated by Django 4.1.3 on 2023-02-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_alter_house_building_type_alter_house_furniture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image10',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image11',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image12',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image13',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image14',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image15',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image16',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image7',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image8',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image9',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.house'),
        ),
    ]
